### ISSUE TITLE
jpm repos are under a different org

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-contribution-notifier#1]
The jpm repos [listed here](https://github.com/mozilla/addons-contribution-notifier/blob/master/src/index.js#L37-L38) should be associated with the [mozilla-jetpack](https://github.com/mozilla-jetpack/) org. I think it would make sense to add all repos within that org. Some are low traffic but [fx-runner](https://github.com/mozilla-jetpack/node-fx-runner/) has some activity since it's also used by `web-ext`.

**Comment by wagnerand** [comment]
Ugh, right, sorry. I added them last minute after your IRC comment yesterday. Would you mind filing a PR that contains all repos you'd like to have added? Thanks!

**Comment by kumar303** [comment]
Sure, added https://github.com/mozilla/addons-contribution-notifier/pull/2
