### ISSUE TITLE
Add name to email subject

### ISSUE THREAD

**Issue by jvillalobos** [mozilla/addons-contribution-notifier#5]
All I really care about is who made the contribution, so it would be very useful to me if the username is also on the subject.

**Comment by jvillalobos** [comment]
Maybe a separate issue, but I think it would be useful to show both the name (Jorge Villalobos) along with the username (jvillalobos) on the email. I'll change this issue to show the name in the subject, which is probably easier to parse.

**Comment by wagnerand** [comment]
Unfortunately, the real name is not exposed in the API response of the pull request. Getting it would require another HTTP request to the github API (which might impact the rate limit threshold).

Adding the username is easy though. @jvillalobos are you ok with that?

**Comment by jvillalobos** [comment]
Yeah, username is good enough.
