### ISSUE TITLE
Not receiving notifications

### ISSUE THREAD

**Issue by caitmuenster** [mozilla/addons-contribution-notifier#8]
Hi there! I just received a report from a contributor that he fixed [this bug](https://github.com/mozilla/addons-server/pull/4030). Unfortunately, I never received a notification from Github that this had been merged. I wasn't sure if the notifier had failed or if the bug fixed hadn't been tagged "good first bug" and wanted to check in. Thank you!

**Comment by wagnerand** [comment]
`Error: No recipients! Exiting.`

Wow. Redis was updated and it didn't tell me.

**Comment by wagnerand** [comment]
Apologies!

I refilled the data, but some old emails got sent again.
